export const GET_ACTIVITY = 'GET_ACTIVITY';
export const GET_COUNTRY= 'GET_COUNTRY';
export const COUNTRY_DETAIL = 'COUNTRY_DETAIL'
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const SEARCH_NAME = 'SEARCH_NAME';
export const FILTER_COUNTRY = 'FILTER_COUNTRY';
export const ORDER_NAME = 'ORDER_NAME';
export const ORDER_POPULATION = 'ORDER_POPULATION';
export const LOADING = 'LOADING';
export const FILTER_CONTINENT = 'FILTER CONTINENT';



